version: "3"
services:
  sejong_classifier:
    container_name: sejong_classifier
    image: sejong_classifier:0.1
    restart: unless-stopped
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - TZ=Asia/Seoul
# multi-line strings in YAML.
# https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
    entrypoint: >
      python3.8 -m entrypoint.run_classifier --local_worker_devices -1
      --kamino_logger debug --reinit_worker_on_exception_while_predict True
    ports:
      - "5000:5000"
    volumes:
      - /home/jun/workspace/Sejong_Classifier/output/klue/bert-base:/app/output/model
      - /home/jun/workspace/Sejong_Classifier/label_classes:/app/label_classes
    networks:
      - sejongnet
networks:
  sejongnet:
